# Generated by Django 3.2.6 on 2021-08-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='category',
            field=models.CharField(default='New Movies', max_length=200),
        ),
    ]
