# Generated by Django 3.2.6 on 2021-08-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_moviedata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='./movie_thumbnail/default.jpg', upload_to='movie_thumbnail'),
        ),
    ]
